CREATE SCHEMA new_db
USE new_db

CREATE TABLE IF NOT EXISTS users(
id INT PRIMARY KEY AUTO_INCREMENT
name VARCHAR(20) NOT NULL,
pass VARCHAR(20) NOT NULL,
email VARCHAR(20) NOT NULL UNIQUE
)

CREATE TABLE IF NOT EXISTS books(
id INT PRIMARY KEY AUTO_INCREMENT
name VARCHAR(20) NOT NULL,
pages INT NOT NULL,
auther VARCHAR(40) NOT NULL
)

CREATE TABLE IF NOT EXISTS addresses(
id INT PRIMARY KEY AUTO_INCREMENT
street VARCHAR(20) NOT NULL,
number INT NOT NULL,
user_id INT,
FOREIGN KEY (user_id) REFERENCES users (id)
)

CREATE TABLE IF NOT EXISTS orders(
id INT PRIMARY KEY AUTO_INCREMENT
amount INT
date DATE NOT NULL,
price INT NOT NULL,
user_id INT,
FOREIGN KEY (user_id) REFERENCES users (id)
)

CREATE TABLE IF NOT EXISTS orders_books(
order_id INT,
book_id INT,
FOREIGN KEY (order_id) REFERENCES orders (id)
FOREIGN KEY (book_id) REFERENCES books (id)
PRIMARY KEY (order_id, book_id)
)


