---
- name: Manage Campus Devices
  hosts: R1
  gather_facts: false
  connection: local

  tasks:
    - name: enable ospf
      ios_config:
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    -  debug: var=print_output

